# Name of workflow
name: Build Workflow

# Triggering this workflow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# Jobs to be run in this workflow
jobs:
 my_first_job:
   name: My First Job
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Repo
       uses: actions/checkout@v2

     - name: Build everything
       run: ./gradlew assemble

     - name: Run ktlint
       run: ./gradlew ktlintCheck

