# Name of workflow
name: Pre Merge Checks

# Triggering this workflow
on:
  push:
    branches:
      - '*'

# Jobs to be run in this workflow
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build project
        run: ./gradlew assembleDebug

      - name: Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/demo-ci-debug-${{ github.head_ref || github.ref_name }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: demo-ci-debug-${{ github.head_ref || github.ref_name }}.apk
          path: app/build/outputs/apk/debug/demo-ci-debug-${{ github.head_ref || github.ref_name }}.apk


  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run all the tests
        run: ./gradlew test

