# Name of workflow
name: Pre Merge Checks

# Triggering this workflow
on:
  push:
    branches:
      - '*'

# Jobs to be run in this workflow
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build project
        run: ./gradlew assembleDebug

      - name: Get current date
        id: get_curr_date
        run: echo "::set-output name=DATE::$(date +'%Y-%m-%d')"
      #        steps.get_curr_date.outputs.DATE

      - name: Get current branch name
        id: get_curr_branch
        run: echo "BRANCH_NAME=${{ github.head_ref || github.ref_name }}" >> $GITHUB_OUTPUT
      #        steps.get_curr_branch.outputs.BRANCH_NAME

      - name: Get APK name
        id: get_apk_name
        run: echo "APK_NAME=demo-ci-debug-${{ steps.get_curr_branch.outputs.BRANCH_NAME }}-${{ steps.get_curr_date.outputs.DATE }}" >> $GITHUB_OUTPUT
      #        steps.get_apk_name.outputs.APK_NAME

      - name: Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/${{ steps.get_apk_name.outputs.APK_NAME }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.get_apk_name.outputs.APK_NAME }}.apk
          path: app/build/outputs/apk/debug/demo-ci-debug-${{ github.head_ref || github.ref_name }}.apk


  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run all the tests
        run: ./gradlew test

