# Name of workflow
name: Pre Merge Checks

# Triggering this workflow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# Jobs to be run in this workflow
jobs:
 ktlint:
   runs-on: 'ubuntu-latest'
   steps:
     - name: Checkout Repo
       uses: actions/checkout@v3

     - name: Run ktlint
       run: ./gradlew ktlintCheck

 test:
   runs-on: 'ubuntu-latest'
   steps:
     - name: Checkout Repo
       uses: actions/checkout@v3

     - name: Run all the tests
       run: ./gradlew test

